name: Api CI

on:
  push:
    branches:
      - '**'
    paths:
      - 'api/**'
      - 'plugins/erxes-plugin-exm-feed/api/**'
      - '.github/workflows/api.yaml'
  pull_request:
    branches:
      - master
      - develop
      - apm
      - crons
      - workers
    paths:
      - 'api/**'
      - '.github/workflows/api.yaml'

jobs:
  api:
    runs-on: ubuntu-18.04

    services:
      mongodb:
        image: mongo:4.0
        ports:
          - 27017:27017

      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        env:
          discovery.type: single-node
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 9200:9200

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.19.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.19.x

      # https://github.com/actions/cache/blob/master/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-api-${{ hashFiles('yarn.lock', 'api/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-api-
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn install
          cd api
          yarn install --frozen-lockfile

      - name: Install plugin dependencies
        run: |
          cd plugins/erxes-plugin-exm-feed/api
          yarn install --frozen-lockfile

      - name: Lint
        run: |
          yarn lint api

      - name: Tsc
        run: |
          cd api
          yarn tsc -p tsconfig.prod.json

      - name: Build
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'push'
        run: |
          cd api
          rm -rf node_modules
          yarn install --frozen-lockfile --production
          yarn build

      - name: Build docker image
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/feat-gantt-chart' || github.ref == 'refs/heads/office' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/crons' || github.ref == 'refs/heads/workers' || github.ref == 'refs/heads/apm')
        env:
          BASE_IMAGE: erxes/erxes-api:base-12.19.1-slim
        run: |
          cd api
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          DOCKER_BUILDKIT=1 docker build --build-arg BASE_IMAGE=$BASE_IMAGE -t erxes/erxes-api:${GITHUB_REF#refs/heads/} -f api.Dockerfile .
          docker push erxes/erxes-api:${GITHUB_REF#refs/heads/}
